name: tsa_rfc3161
description: "This is a TSA (Time Stamping Authority) client/library RFC3161 for Flutter apps. With it, you can timestamp any files or any text message"

repository: https://github.com/ysimonx/tsa_rfc3161

topics: 
  - tsa
  - rfc3161
  - digicert
  - certigna
  - timestamp
version: 1.0.3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  file_picker: ^8.0.0+1
  crypto: ^3.0.3
  http: ^1.2.0
  asn1lib: ^1.5.3
  dio: ^5.7.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  test: ^1.25.7

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
